// <auto-generated />
using System;
using APIListaContatos.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace APIListaContatos.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220814154814_PopulaTabelas")]
    partial class PopulaTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("APIListaContatos.Models.Contato", b =>
                {
                    b.Property<int>("ContatoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContatoId"), 1L, 1);

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("PessoaId")
                        .HasColumnType("int");

                    b.HasKey("ContatoId");

                    b.HasIndex("PessoaId");

                    b.ToTable("Contatos");

                    b.HasData(
                        new
                        {
                            ContatoId = 1,
                            Conteudo = "11946574829",
                            Nome = "Telefone",
                            PessoaId = 1
                        },
                        new
                        {
                            ContatoId = 2,
                            Conteudo = "carlos.augusto@gmail.com",
                            Nome = "Email",
                            PessoaId = 2
                        },
                        new
                        {
                            ContatoId = 3,
                            Conteudo = "11966935487",
                            Nome = "Whatsapp",
                            PessoaId = 3
                        });
                });

            modelBuilder.Entity("APIListaContatos.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaId"), 1L, 1);

                    b.Property<int?>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoas");

                    b.HasData(
                        new
                        {
                            PessoaId = 1,
                            Idade = 20,
                            Nome = "Fernando",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            PessoaId = 2,
                            Idade = 30,
                            Nome = "Carlos",
                            Sexo = "Masculino"
                        },
                        new
                        {
                            PessoaId = 3,
                            Idade = 23,
                            Nome = "Roberta",
                            Sexo = "Feminino"
                        });
                });

            modelBuilder.Entity("APIListaContatos.Models.Contato", b =>
                {
                    b.HasOne("APIListaContatos.Models.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("APIListaContatos.Models.Pessoa", b =>
                {
                    b.Navigation("Contatos");
                });
#pragma warning restore 612, 618
        }
    }
}
